name: Build and Publish Docker Image

permissions:
  contents: read
  packages: write

on:
  workflow_call:
    inputs:
      project_path:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      image_name:
        required: true
        type: string
    outputs:
      image_tag:
        description: 'The built image tag'
        value: ${{ jobs.build-and-publish.outputs.image_tag }}
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.write_image_tag.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '9.0.x'

      - name: Build
        run: dotnet build --configuration Release ${{ inputs.project_path }}

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish ${{ inputs.project_path }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ inputs.image_name }}:${{ github.sha }} -f ${{ inputs.dockerfile_path }} .

      - name: Push Docker image to GitHub Container Registry
        id: push_image
        run: |
          docker push ${{ inputs.image_name }}:${{ github.sha }}
          echo "IMAGE_FULL_NAME=${{ inputs.image_name }}:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Write image tag to output
        id: write_image_tag
        run: |
          echo "image_tag=${{ inputs.image_name }}:${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "${{ inputs.image_name }}:${{ github.sha }}" > image_full_name.txt
          echo "Image name written to image_full_name.txt"