name: CI/CD Pipeline


permissions:
  contents: read
  packages: write
  
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-publish:
    uses: DomainSoftware/AcmeTickets2025/.github/workflows/docker-image.yml@master
    secrets: inherit

  deploy-app:
    needs: build-and-publish
    uses: DomainSoftware/AcmeTickets2025/.github/workflows/deployapp.yml@master
    secrets: inherit
    with:
      image_tag: ${{ needs.build-and-publish.outputs.image_tag }}
