name: Deploy Azure Container App

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: acmetickets_rg
  CONTAINER_APP_NAME: acmetickets2025-app
  CONTAINERAPPS_ENVIRONMENT: acmetickets_dev
  AZURE_LOCATION: eastus

jobs:
  deploy-container-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check for Azure Container App
        id: check_aca
        run: |
          result=$(az containerapp show --name "$CONTAINER_APP_NAME" --resource-group "$RESOURCE_GROUP" --query "name" --output tsv 2>/dev/null || echo "notfound")
          echo "result=$result" >> $GITHUB_OUTPUT

      - name: Fail if Container App does not exist
        if: steps.check_aca.outputs.result == 'notfound'
        run: |
          echo "Azure Container App not found. Please provision it before deploying."
          exit 1

      - name: Create Azure Container Apps Environment
        run: |
          az containerapp env create \
            --name "$CONTAINERAPPS_ENVIRONMENT" \
            --resource-group "$RESOURCE_GROUP" \
            --location "$AZURE_LOCATION"
          echo "Azure Container Apps Environment provisioned."

    #   - name: Provision Azure Container App
    #     run: |
    #       az containerapp create \
    #         --name "$CONTAINER_APP_NAME" \
    #         --resource-group "$RESOURCE_GROUP" \
    #         --environment "$CONTAINERAPPS_ENVIRONMENT" \
    #         --image <your-image-name>:<tag> \
    #         --ingress external \
    #         --target-port 5271
    #       echo "Azure Container App provisioned."

    #   - name: Deploy to Azure Container App
    #     if: steps.check_aca.outputs.result != 'notfound'
    #     run: |
    #       echo "Deploying to Azure Container App..."
