name: Deploy App to Azure Container App

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Full image name (e.g. ghcr.io/org/repo:tag)'
        required: true
        type: string

env:
  RESOURCE_GROUP: acmetickets_rg
  CONTAINER_APP_NAME: acmetickets2025-app
  CONTAINERAPPS_ENVIRONMENT: acmeticketsacadev
  AZURE_LOCATION: eastus

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check if Azure Container App exists
        id: check_aca
        run: |
          result=$(az containerapp show --name "$CONTAINER_APP_NAME" --resource-group "$RESOURCE_GROUP" --query "name" --output tsv 2>/dev/null || echo "notfound")
          echo "result=$result" >> $GITHUB_OUTPUT

      - name: Create Azure Container App if not exists
        if: steps.check_aca.outputs.result == 'notfound'
        run: |
          az containerapp create \
            --name "$CONTAINER_APP_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --environment "$CONTAINERAPPS_ENVIRONMENT" \
            --image "${{ github.event.inputs.image_name }}" \
            --ingress external \
            --target-port 5271 \
            --env-vars ASPNETCORE_ENVIRONMENT=Development
          echo "Azure Container App created."

      - name: Update Azure Container App if exists
        if: steps.check_aca.outputs.result != 'notfound'
        run: |
          az containerapp update \
            --name "$CONTAINER_APP_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --image "${{ github.event.inputs.image_name }}" \
            --set-env-vars ASPNETCORE_ENVIRONMENT=Development
          echo "Azure Container App updated."
